#!/bin/env python

import os 
import sys

args = ''
l = len(sys.argv)
i = 1
while i < l:
  args += ' '
  args += sys.argv[i]
  i += 1

os.system('cd /usr/share/rpmanager/; ./rpmanager-wizard' + args)
