#!/bin/sh

## Startap script written by Charles Barcza for blackPanther OS
## Copryright 2005-2016

if [ "$LANG" = "hu_HU.UTF-8" ];then
    warning="Ez a változat egy tesztverzió! A helyes működés nem garantált..."
    else
    warning="This is the release an test version! The correct work not garantied..."
fi

SU=`which gksu 2>/dev/null || which gnomesu 2>/dev/null || which gsu 2>/dev/null || which kdesu 2>/dev/null || echo "Error1"`

if [ "$SU" = Error1 ]
then 
 if [[ -n "$KDE_FULL_SESSION" ]];then
    mess="kdialog --error"
  else
    mess="zenity --error --text"
 fi
    [ ! -n $DISPLAY ]&& echo "[Warning! The SU manager not found. Please check your installation]"
    [ -n $DISPLAY ]&& $mess "Please restart RPManager with root rights or install kdesu or gnomesu.."
    exit 
fi

if [[ -n "$KDE_FULL_SESSION" ]];then
    mess="kdialog --sorry"
  else
    mess="zenity --error --text"
fi


if [ "$UID" = "0" ]; then
    $mess "$warning"
    cd /usr/share/rpmanager
    python ./rpmanager
 else
    kdesu -c /usr/bin/programkezelo
    exit 1
fi

